language: java
jdk:
- oraclejdk8
sudo: required

services: 
  - docker

before script:
  - docker run -d -p 4444:4444 selenium/standalone-chrome:3.0.1-aluminum

script: gradle check
branches:
only: develop

notifications:
  email: true
  recipients:
  - Ericka.Viraca@fundacion-jala.org
