language: java
jdk:
- oraclejdk8
sudo: required

services: 
  -docker

before install:
  - docker pull erickaviraca/docker

script: gradle check
branches:
only: develop

notifications:
  email: true
  recipients:
  - Ericka.Viraca@fundacion-jala.org
