language: java
jdk:
- oraclejdk8
sudo: required

services: 
  - docker

before_install:
  - docker info
  - docker build -t test:local ./Test

script: gradle check
branches:
only: develop

notifications:
  email: true
  recipients:
  - Ericka.Viraca@fundacion-jala.org
