language: java
jdk:
- oraclejdk8
sudo: required

services: 
  -docker

script: gradle check
branches:
only: develop

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org
